name: version_checker
description: "A new Flutter project."
publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  package_info_plus: ^8.0.0
  http: ^1.2.2
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true